name: The Ecology of Technology
favicon: null
layout_spectrum: 0.30821
typography_spectrum: 0.77639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#380d38'
    - '#8ac33f'
    - '#80287a'
    - '#c6d929'
  brandStrength: 0.951404519379139
  lightness: 0.9904071262571961
  saturation: 0.21380541031248868
  rhythmicContrast: 0.9222929028328508
purpose: []
